services:
  db:
    image: postgres:latest
    container_name: hospital-system-api-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - hospital_system_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-system-api-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    extra_hosts:
      - "localhost:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: hospital-system-api-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped

volumes:
  hospital_system_postgres_data:

